USE TPC_EQUIPO_5
-- Volcar la base de datos para la tabla `provincias`
--

INSERT INTO Provincias (Nombre) VALUES
('Buenos Aires'),
('Buenos Aires-GBA'),
('Capital Federal'),
('Catamarca'),
('Chaco'),
('Chubut'),
('Córdoba'),
('Corrientes'),
('Entre Ríos'),
('Formosa'),
('Jujuy'),
('La Pampa'),
('La Rioja'),
('Mendoza'),
('Misiones'),
('Neuquén'),
('Río Negro'),
('Salta'),
('San Juan'),
('San Luis'),
('Santa Cruz'),
('Santa Fe'),
('Santiago del Estero'),
('Tierra del Fuego'),
('Tucumán');


--
-- Estructura de tabla para la tabla `localidades`
----
-- Volcar la base de datos para la tabla `localidades`
--

INSERT INTO Ciudades (IDProvincia, nombre) VALUES
(1, '25 de Mayo'),
(1, '3 de febrero'),
(1, 'A. Alsina'),
(1, 'A. Gonzáles Cháves'),
(1, 'Aguas Verdes'),
(1, 'Alberti'),
(1, 'Arrecifes'),
(1, 'Ayacucho'),
(1, 'Azul'),
(1, 'Bahía Blanca'),
(1, 'Balcarce'),
(1, 'Baradero'),
(1, 'Benito Juárez'),
(1, 'Berisso'),
(1, 'Bolívar'),
(1, 'Bragado'),
(1, 'Brandsen'),
(1, 'Campana'),
(1, 'Cañuelas'),
(1, 'Capilla del Señor'),
(1, 'Capitán Sarmiento'),
(1, 'Carapachay'),
(1, 'Carhue'),
(1, 'Cariló'),
(1, 'Carlos Casares'),
(1, 'Carlos Tejedor'),
(1, 'Carmen de Areco'),
(1, 'Carmen de Patagones'),
(1, 'Castelli'),
(1, 'Chacabuco'),
(1, 'Chascomús'),
(1, 'Chivilcoy'),
(1, 'Colón'),
(1, 'Coronel Dorrego'),
(1, 'Coronel Pringles'),
(1, 'Coronel Rosales'),
(1, 'Coronel Suarez'),
(1, 'Costa Azul'),
(1, 'Costa Chica'),
(1, 'Costa del Este'),
(1, 'Costa Esmeralda'),
(1, 'Daireaux'),
(1, 'Darregueira'),
(1, 'Del Viso'),
(1, 'Dolores'),
(1, 'Don Torcuato'),
(1, 'Ensenada'),
(1, 'Escobar'),
(1, 'Exaltación de la Cruz'),
(1, 'Florentino Ameghino'),
(1, 'Garín'),
(1, 'Gral. Alvarado'),
(1, 'Gral. Alvear'),
(1, 'Gral. Arenales'),
(1, 'Gral. Belgrano'),
(1, 'Gral. Guido'),
(1, 'Gral. Lamadrid'),
(1, 'Gral. Las Heras'),
(1, 'Gral. Lavalle'),
(1, 'Gral. Madariaga'),
(1, 'Gral. Pacheco'),
(1, 'Gral. Paz'),
(1, 'Gral. Pinto'),
(1, 'Gral. Pueyrredón'),
(1, 'Gral. Rodríguez'),
(1, 'Gral. Viamonte'),
(1, 'Gral. Villegas'),
(1, 'Guaminí'),
(1, 'Guernica'),
(1, 'Hipólito Yrigoyen'),
(1, 'Ing. Maschwitz'),
(1, 'Junín'),
(1, 'La Plata'),
(1, 'Laprida'),
(1, 'Las Flores'),
(1, 'Las Toninas'),
(1, 'Leandro N. Alem'),
(1, 'Lincoln'),
(1, 'Loberia'),
(1, 'Lobos'),
(1, 'Los Cardales'),
(1, 'Los Toldos'),
(1, 'Lucila del Mar'),
(1, 'Luján'),
(1, 'Magdalena'),
(1, 'Maipú'),
(1, 'Mar Chiquita'),
(1, 'Mar de Ajó'),
(1, 'Mar de las Pampas'),
(1, 'Mar del Plata'),
(1, 'Mar del Tuyú'),
(1, 'Marcos Paz'),
(1, 'Mercedes'),
(1, 'Miramar'),
(1, 'Monte'),
(1, 'Monte Hermoso'),
(1, 'Munro'),
(1, 'Navarro'),
(1, 'Necochea'),
(1, 'Olavarría'),
(1, 'Partido de la Costa'),
(1, 'Pehuajó'),
(1, 'Pellegrini'),
(1, 'Pergamino'),
(1, 'Pigüé'),
(1, 'Pila'),
(1, 'Pilar'),
(1, 'Pinamar'),
(1, 'Pinar del Sol'),
(1, 'Polvorines'),
(1, 'Pte. Perón'),
(1, 'Puán'),
(1, 'Punta Indio'),
(1, 'Ramallo'),
(1, 'Rauch'),
(1, 'Rivadavia'),
(1, 'Rojas'),
(1, 'Roque Pérez'),
(1, 'Saavedra'),
(1, 'Saladillo'),
(1, 'Salliquel�'),
(1, 'Salto'),
(1, 'San Andr�s de Giles'),
(1, 'San Antonio de Areco'),
(1, 'San Antonio de Padua'),
(1, 'San Bernardo'),
(1, 'San Cayetano'),
(1, 'San Clemente del Tuyú'),
(1, 'San Nicolás'),
(1, 'San Pedro'),
(1, 'San Vicente'),
(1, 'Santa Teresita'),
(1, 'Suipacha'),
(1, 'Tandil'),
(1, 'Tapalqu�'),
(1, 'Tordillo'),
(1, 'Tornquist'),
(1, 'Trenque Lauquen'),
(1, 'Tres Lomas'),
(1, 'Villa Gesell'),
(1, 'Villarino'),
(1, 'Zárate'),
(2, '11 de Septiembre'),
(2, '20 de Junio'),
(2, '25 de Mayo'),
(2, 'Acassuso'),
(2, 'Adrogué'),
(2, 'Aldo Bonzi'),
(2, 'área Reserva Cinturón Ecológico'),
(2, 'Avellaneda'),
(2, 'Banfield'),
(2, 'Barrio Parque'),
(2, 'Barrio Santa Teresita'),
(2, 'Beccar'),
(2, 'Bella Vista'),
(2, 'Berazategui'),
(2, 'Bernal Este'),
(2, 'Bernal Oeste'),
(2, 'Billinghurst'),
(2, 'Boulogne'),
(2, 'Burzaco'),
(2, 'Carapachay'),
(2, 'Caseros'),
(2, 'Castelar'),
(2, 'Churruca'),
(2, 'Ciudad Evita'),
(2, 'Ciudad Madero'),
(2, 'Ciudadela'),
(2, 'Claypole'),
(2, 'Crucecita'),
(2, 'Dock Sud'),
(2, 'Don Bosco'),
(2, 'Don Orione'),
(2, 'El Jag�el'),
(2, 'El Libertador'),
(2, 'El Palomar'),
(2, 'El Tala'),
(2, 'El Trébol'),
(2, 'Ezeiza'),
(2, 'Ezpeleta'),
(2, 'Florencio Varela'),
(2, 'Florida'),
(2, 'Francisco álvarez'),
(2, 'Gerli'),
(2, 'Glew'),
(2, 'González Catán'),
(2, 'Gral. Lamadrid'),
(2, 'Grand Bourg'),
(2, 'Gregorio de Laferrere'),
(2, 'Guillermo Enrique Hudson'),
(2, 'Haedo'),
(2, 'Hurlingham'),
(2, 'Ing. Sourdeaux'),
(2, 'Isidro Casanova'),
(2, 'Ituzaingó'),
(2, 'José C. Paz'),
(2, 'José Ingenieros'),
(2, 'José Marmol'),
(2, 'La Lucila'),
(2, 'La Reja'),
(2, 'La Tablada'),
(2, 'Lanús'),
(2, 'Llavallol'),
(2, 'Loma Hermosa'),
(2, 'Lomas de Zamora'),
(2, 'Lomas del Millón'),
(2, 'Lomas del Mirador'),
(2, 'Longchamps'),
(2, 'Los Polvorines'),
(2, 'Luis Guill�n'),
(2, 'Malvinas Argentinas'),
(2, 'Martín Coronado'),
(2, 'Martínez'),
(2, 'Merlo'),
(2, 'Ministro Rivadavia'),
(2, 'Monte Chingolo'),
(2, 'Monte Grande'),
(2, 'Moreno'),
(2, 'Morín'),
(2, 'Muñiz'),
(2, 'Olivos'),
(2, 'Pablo Nogués'),
(2, 'Pablo Podest�'),
(2, 'Paso del Rey'),
(2, 'Pereyra'),
(2, 'Pi�eiro'),
(2, 'Pl�tanos'),
(2, 'Pontevedra'),
(2, 'Quilmes'),
(2, 'Rafael Calzada'),
(2, 'Rafael Castillo'),
(2, 'Ramos Mej�a'),
(2, 'Ranelagh'),
(2, 'Remedios de Escalada'),
(2, 'Sáenz Peña'),
(2, 'San Antonio de Padua'),
(2, 'San Fernando'),
(2, 'San Francisco Solano'),
(2, 'San Isidro'),
(2, 'San José'),
(2, 'San Justo'),
(2, 'San Martín'),
(2, 'San Miguel'),
(2, 'Santos Lugares'),
(2, 'Sarandí'),
(2, 'Sourigues'),
(2, 'Tapiales'),
(2, 'Temperley'),
(2, 'Tigre'),
(2, 'Tortuguitas'),
(2, 'Trist�n Suárez'),
(2, 'Trujui'),
(2, 'Turdera'),
(2, 'Valentín Alsina'),
(2, 'Vicente López'),
(2, 'Villa Adelina'),
(2, 'Villa Ballester'),
(2, 'Villa Bosch'),
(2, 'Villa Caraza'),
(2, 'Villa Celina'),
(2, 'Villa Centenario'),
(2, 'Villa de Mayo'),
(2, 'Villa Diamante'),
(2, 'Villa Domínico'),
(2, 'Villa España'),
(2, 'Villa Fiorito'),
(2, 'Villa Guillermina'),
(2, 'Villa Insuperable'),
(2, 'Villa José León Suárez'),
(2, 'Villa La Florida'),
(2, 'Villa Luzuriaga'),
(2, 'Villa Martelli'),
(2, 'Villa Obrera'),
(2, 'Villa Progreso'),
(2, 'Villa Raffo'),
(2, 'Villa Sarmiento'),
(2, 'Villa Tesei'),
(2, 'Villa Udaondo'),
(2, 'Virrey del Pino'),
(2, 'Wilde'),
(2, 'William Morris'),
(3, 'Agronomía'),
(3, 'Almagro'),
(3, 'Balvanera'),
(3, 'Barracas'),
(3, 'Belgrano'),
(3, 'Boca'),
(3, 'Boedo'),
(3, 'Caballito'),
(3, 'Chacarita'),
(3, 'Coghlan'),
(3, 'Colegiales'),
(3, 'Constitución'),
(3, 'Flores'),
(3, 'Floresta'),
(3, 'La Paternal'),
(3, 'Liniers'),
(3, 'Mataderos'),
(3, 'Monserrat'),
(3, 'Monte Castro'),
(3, 'Nueva Pompeya'),
(3, 'Núñez'),
(3, 'Palermo'),
(3, 'Parque Avellaneda'),
(3, 'Parque Chacabuco'),
(3, 'Parque Chas'),
(3, 'Parque Patricios'),
(3, 'Puerto Madero'),
(3, 'Recoleta'),
(3, 'Retiro'),
(3, 'Saavedra'),
(3, 'San Cristóbal'),
(3, 'San Nicolás'),
(3, 'San Telmo'),
(3, 'Vélez Sársfield'),
(3, 'Versalles'),
(3, 'Villa Crespo'),
(3, 'Villa del Parque'),
(3, 'Villa Devoto'),
(3, 'Villa Gral. Mitre'),
(3, 'Villa Lugano'),
(3, 'Villa Luro'),
(3, 'Villa Ortízar'),
(3, 'Villa Pueyrredón'),
(3, 'Villa Real'),
(3, 'Villa Riachuelo'),
(3, 'Villa Santa Rita'),
(3, 'Villa Soldati'),
(3, 'Villa Urquiza'),
(4, 'Aconquija'),
(4, 'Ancasti'),
(4, 'Andalgal�'),
(4, 'Antofagasta'),
(4, 'Belén'),
(4, 'Capay�n'),
(4, 'Capital'),
(4, '4'),
(4, 'Corral Quemado'),
(4, 'El Alto'),
(4, 'El Rodeo'),
(4, 'F.Mamerto Esqui�'),
(4, 'Fiambal�'),
(4, 'Hualf�n'),
(4, 'Huillapima'),
(4, 'Ica�o'),
(4, 'La Puerta'),
(4, 'Las Juntas'),
(4, 'Londres'),
(4, 'Los Altos'),
(4, 'Los Varela'),
(4, 'Mutqu�n'),
(4, 'Pacl�n'),
(4, 'Poman'),
(4, 'Pozo de La Piedra'),
(4, 'Puerta de Corral'),
(4, 'Puerta San José'),
(4, 'Recreo'),
(4, 'S.F.V de 4'),
(4, 'San Fernando'),
(4, 'San Fernando del Valle'),
(4, 'San José'),
(4, 'Santa María'),
(4, 'Santa Rosa'),
(4, 'Saujil'),
(4, 'Tapso'),
(4, 'Tinogasta'),
(4, 'Valle Viejo'),
(4, 'Villa Vil'),
(5, 'Avi� Tera�'),
(5, 'Barranqueras'),
(5, 'Basail'),
(5, 'Campo Largo'),
(5, 'Capital'),
(5, 'Capitán Solari'),
(5, 'Charadai'),
(5, 'Charata'),
(5, 'Chorotis'),
(5, 'Ciervo Petiso'),
(5, 'Cnel. Du Graty'),
(5, 'Col. Benítez'),
(5, 'Col. Elisa'),
(5, 'Col. Popular'),
(5, 'Colonias Unidas'),
(5, 'Concepción'),
(5, 'Corzuela'),
(5, 'Cote Lai'),
(5, 'El Sauzalito'),
(5, 'Enrique Urien'),
(5, 'Fontana'),
(5, 'Fte. Esperanza'),
(5, 'Gancedo'),
(5, 'Gral. Capdevila'),
(5, 'Gral. Pinero'),
(5, 'Gral. San Martín'),
(5, 'Gral. Vedia'),
(5, 'Hermoso Campo'),
(5, 'I. del Cerrito'),
(5, 'J.J. Castelli'),
(5, 'La Clotilde'),
(5, 'La Eduvigis'),
(5, 'La Escondida'),
(5, 'La Leonesa'),
(5, 'La Tigra'),
(5, 'La Verde'),
(5, 'Laguna Blanca'),
(5, 'Laguna Limpia'),
(5, 'Lapachito'),
(5, 'Las Bre�as'),
(5, 'Las Garcitas'),
(5, 'Las Palmas'),
(5, 'Los Frentones'),
(5, 'Machagai'),
(5, 'Makall�'),
(5, 'Margarita Belén'),
(5, 'Miraflores'),
(5, 'Misión N. Pompeya'),
(5, 'Napenay'),
(5, 'Pampa Almirón'),
(5, 'Pampa del Indio'),
(5, 'Pampa del Infierno'),
(5, 'Pdcia. de La Plaza'),
(5, 'Pdcia. Roca'),
(5, 'Pdcia. Roque Sáenz Peña'),
(5, 'Pto. Bermejo'),
(5, 'Pto. Eva Perón'),
(5, 'Puero Tirol'),
(5, 'Puerto Vilelas'),
(5, 'Quitilipi'),
(5, 'Resistencia'),
(5, 'Sáenz Peña'),
(5, 'Samuh�'),
(5, 'San Bernardo'),
(5, 'Santa Sylvina'),
(5, 'Taco Pozo'),
(5, 'Tres Isletas'),
(5, 'Villa Ángela'),
(5, 'Villa Berthet'),
(5, 'Villa R. Bermejito'),
(6, 'Aldea Apeleg'),
(6, 'Aldea Beleiro'),
(6, 'Aldea Epulef'),
(6, 'Alto Río Sengerr'),
(6, 'Buen Pasto'),
(6, 'Camarones'),
(6, 'Carrenleuf�'),
(6, 'Cholila'),
(6, 'Co. Centinela'),
(6, 'Colan Conhu�'),
(6, 'Comodoro Rivadavia'),
(6, 'Corcovado'),
(6, 'Cushamen'),
(6, 'Dique F. Ameghino'),
(6, 'Dolav�n'),
(6, 'Dr. R. Rojas'),
(6, 'El Hoyo'),
(6, 'El Mait�n'),
(6, 'Epuy�n'),
(6, 'Esquel'),
(6, 'Facundo'),
(6, 'Gaim�n'),
(6, 'Gan Gan'),
(6, 'Gastre'),
(6, 'Gdor. Costa'),
(6, 'Gualjaina'),
(6, 'J. de San Martín'),
(6, 'Lago Blanco'),
(6, 'Lago Puelo'),
(6, 'Lagunita Salada'),
(6, 'Las Plumas'),
(6, 'Los Altares'),
(6, 'Paso de los Indios'),
(6, 'Paso del Sapo'),
(6, 'Pto. Madryn'),
(6, 'Pto. Pirámides'),
(6, 'Rada Tilly'),
(6, 'Rawson'),
(6, 'Río Mayo'),
(6, 'Río Pico'),
(6, 'Sarmiento'),
(6, 'Tecka'),
(6, 'Telsen'),
(6, 'Trelew'),
(6, 'Trevelin'),
(6, 'Veintiocho de Julio'),
(7, 'Achiras'),
(7, 'Adelia Maria'),
(7, 'Agua de Oro'),
(7, 'Alcira Gigena'),
(7, 'Aldea Santa Maria'),
(7, 'Alejandro Roca'),
(7, 'Alejo Ledesma'),
(7, 'Alicia'),
(7, 'Almafuerte'),
(7, 'Alpa Corral'),
(7, 'Alta Gracia'),
(7, 'Alto Alegre'),
(7, 'Alto de Los Quebrachos'),
(7, 'Altos de Chipion'),
(7, 'Amboy'),
(7, 'Ambul'),
(7, 'Ana Zumaran'),
(7, 'Anisacate'),
(7, 'Arguello'),
(7, 'Arias'),
(7, 'Arroyito'),
(7, 'Arroyo Algodon'),
(7, 'Arroyo Cabral'),
(7, 'Arroyo Los Patos'),
(7, 'Assunta'),
(7, 'Atahona'),
(7, 'Ausonia'),
(7, 'Avellaneda'),
(7, 'Ballesteros'),
(7, 'Ballesteros Sud'),
(7, 'Balnearia'),
(7, 'Ba�ado de Soto'),
(7, 'Bell Ville'),
(7, 'Bengolea'),
(7, 'Benjamin Gould'),
(7, 'Berrotaran'),
(7, 'Bialet Masse'),
(7, 'Bouwer'),
(7, 'Brinkmann'),
(7, 'Buchardo'),
(7, 'Bulnes'),
(7, 'Cabalango'),
(7, 'Calamuchita'),
(7, 'Calchin'),
(7, 'Calchin Oeste'),
(7, 'Calmayo'),
(7, 'Camilo Aldao'),
(7, 'Caminiaga'),
(7, 'Ca�ada de Luque'),
(7, 'Ca�ada de Machado'),
(7, 'Ca�ada de Rio Pinto'),
(7, 'Ca�ada del Sauce'),
(7, 'Canals'),
(7, 'Candelaria Sud'),
(7, 'Capilla de Remedios'),
(7, 'Capilla de Siton'),
(7, 'Capilla del Carmen'),
(7, 'Capilla del Monte'),
(7, 'Capital'),
(7, 'Capitan Gral B. O�Higgins'),
(7, 'Carnerillo'),
(7, 'Carrilobo'),
(7, 'Casa Grande'),
(7, 'Cavanagh'),
(7, 'Cerro Colorado'),
(7, 'Chaj�n'),
(7, 'Chalacea'),
(7, 'Cha�ar Viejo'),
(7, 'Chancan�'),
(7, 'Charbonier'),
(7, 'Charras'),
(7, 'Chaz�n'),
(7, 'Chilibroste'),
(7, 'Chucul'),
(7, 'Chu�a'),
(7, 'Chu�a Huasi'),
(7, 'Churqui Ca�ada'),
(7, 'Cienaga Del Coro'),
(7, 'Cintra'),
(7, 'Col. Almada'),
(7, 'Col. Anita'),
(7, 'Col. Barge'),
(7, 'Col. Bismark'),
(7, 'Col. Bremen'),
(7, 'Col. Caroya'),
(7, 'Col. Italiana'),
(7, 'Col. Iturraspe'),
(7, 'Col. Las Cuatro Esquinas'),
(7, 'Col. Las Pichanas'),
(7, 'Col. Marina'),
(7, 'Col. Prosperidad'),
(7, 'Col. San Bartolome'),
(7, 'Col. San Pedro'),
(7, 'Col. Tirolesa'),
(7, 'Col. Vicente Aguero'),
(7, 'Col. Videla'),
(7, 'Col. Vignaud'),
(7, 'Col. Waltelina'),
(7, 'Colazo'),
(7, 'Comechingones'),
(7, 'Conlara'),
(7, 'Copacabana'),
(7, '7'),
(7, 'Coronel Baigorria'),
(7, 'Coronel Moldes'),
(7, 'Corral de Bustos'),
(7, 'Corralito'),
(7, 'Cosqu�n'),
(7, 'Costa Sacate'),
(7, 'Cruz Alta'),
(7, 'Cruz de Ca�a'),
(7, 'Cruz del Eje'),
(7, 'Cuesta Blanca'),
(7, 'Dean Funes'),
(7, 'Del Campillo'),
(7, 'Despe�aderos'),
(7, 'Devoto'),
(7, 'Diego de Rojas'),
(7, 'Dique Chico'),
(7, 'El Ara�ado'),
(7, 'El Brete'),
(7, 'El Chacho'),
(7, 'El Crisp�n'),
(7, 'El Fort�n'),
(7, 'El Manzano'),
(7, 'El Rastreador'),
(7, 'El Rodeo'),
(7, 'El T�o'),
(7, 'Elena'),
(7, 'Embalse'),
(7, 'Esquina'),
(7, 'Estaci�n Gral. Paz'),
(7, 'Estaci�n Ju�rez Celman'),
(7, 'Estancia de Guadalupe'),
(7, 'Estancia Vieja'),
(7, 'Etruria'),
(7, 'Eufrasio Loza'),
(7, 'Falda del Carmen'),
(7, 'Freyre'),
(7, 'Gral. Baldissera'),
(7, 'Gral. Cabrera'),
(7, 'Gral. Deheza'),
(7, 'Gral. Fotheringham'),
(7, 'Gral. Levalle'),
(7, 'Gral. Roca'),
(7, 'Guanaco Muerto'),
(7, 'Guasapampa'),
(7, 'Guatimozin'),
(7, 'Gutenberg'),
(7, 'Hernando'),
(7, 'Huanchillas'),
(7, 'Huerta Grande'),
(7, 'Huinca Renanco'),
(7, 'Idiazabal'),
(7, 'Impira'),
(7, 'Inriville'),
(7, 'Isla Verde'),
(7, 'Ital�'),
(7, 'James Craik'),
(7, 'Jes�s Mar�a'),
(7, 'Jovita'),
(7, 'Justiniano Posse'),
(7, 'Km 658'),
(7, 'L. V. Mansilla'),
(7, 'La Batea'),
(7, 'La Calera'),
(7, 'La Carlota'),
(7, 'La Carolina'),
(7, 'La Cautiva'),
(7, 'La Cesira'),
(7, 'La Cruz'),
(7, 'La Cumbre'),
(7, 'La Cumbrecita'),
(7, 'La Falda'),
(7, 'La Francia'),
(7, 'La Granja'),
(7, 'La Higuera'),
(7, 'La Laguna'),
(7, 'La Paisanita'),
(7, 'La Palestina'),
(7, '12'),
(7, 'La Paquita'),
(7, 'La Para'),
(7, 'La Paz'),
(7, 'La Playa'),
(7, 'La Playosa'),
(7, 'La Poblaci�n'),
(7, 'La Posta'),
(7, 'La Puerta'),
(7, 'La Quinta'),
(7, 'La Rancherita'),
(7, 'La Rinconada'),
(7, 'La Serranita'),
(7, 'La Tordilla'),
(7, 'Laborde'),
(7, 'Laboulaye'),
(7, 'Laguna Larga'),
(7, 'Las Acequias'),
(7, 'Las Albahacas'),
(7, 'Las Arrias'),
(7, 'Las Bajadas'),
(7, 'Las Caleras'),
(7, 'Las Calles'),
(7, 'Las Ca�adas'),
(7, 'Las Gramillas'),
(7, 'Las Higueras'),
(7, 'Las Isletillas'),
(7, 'Las Junturas'),
(7, 'Las Palmas'),
(7, 'Las Pe�as'),
(7, 'Las Pe�as Sud'),
(7, 'Las Perdices'),
(7, 'Las Playas'),
(7, 'Las Rabonas'),
(7, 'Las Saladas'),
(7, 'Las Tapias'),
(7, 'Las Varas'),
(7, 'Las Varillas'),
(7, 'Las Vertientes'),
(7, 'Leguizam�n'),
(7, 'Leones'),
(7, 'Los Cedros'),
(7, 'Los Cerrillos'),
(7, 'Los Cha�aritos (C.E)'),
(7, 'Los Chanaritos (R.S)'),
(7, 'Los Cisnes'),
(7, 'Los Cocos'),
(7, 'Los C�ndores'),
(7, 'Los Hornillos'),
(7, 'Los Hoyos'),
(7, 'Los Mistoles'),
(7, 'Los Molinos'),
(7, 'Los Pozos'),
(7, 'Los Reartes'),
(7, 'Los Surgentes'),
(7, 'Los Talares'),
(7, 'Los Zorros'),
(7, 'Lozada'),
(7, 'Luca'),
(7, 'Luque'),
(7, 'Luyaba'),
(7, 'Malague�o'),
(7, 'Malena'),
(7, 'Malvinas Argentinas'),
(7, 'Manfredi'),
(7, 'Maquinista Gallini'),
(7, 'Marcos Ju�rez'),
(7, 'Marull'),
(7, 'Matorrales'),
(7, 'Mattaldi'),
(7, 'Mayu Sumaj'),
(7, 'Media Naranja'),
(7, 'Melo'),
(7, 'Mendiolaza'),
(7, 'Mi Granja'),
(7, 'Mina Clavero'),
(7, 'Miramar'),
(7, 'Morrison'),
(7, 'Morteros'),
(7, 'Mte. Buey'),
(7, 'Mte. Cristo'),
(7, 'Mte. De Los Gauchos'),
(7, 'Mte. Le�a'),
(7, 'Mte. Ma�z'),
(7, 'Mte. Ralo'),
(7, 'Nicol�s Bruzone'),
(7, 'Noetinger'),
(7, 'Nono'),
(7, 'Nueva 7'),
(7, 'Obispo Trejo'),
(7, 'Olaeta'),
(7, 'Oliva'),
(7, 'Olivares San Nicol�s'),
(7, 'Onagolty'),
(7, 'Oncativo'),
(7, 'Ordo�ez'),
(7, 'Pacheco De Melo'),
(7, 'Pampayasta N.'),
(7, 'Pampayasta S.'),
(7, 'Panaholma'),
(7, 'Pascanas'),
(7, 'Pasco'),
(7, 'Paso del Durazno'),
(7, 'Paso Viejo'),
(7, 'Pilar'),
(7, 'Pinc�n'),
(7, 'Piquill�n'),
(7, 'Plaza de Mercedes'),
(7, 'Plaza Luxardo'),
(7, 'Porte�a'),
(7, 'Potrero de Garay'),
(7, 'Pozo del Molle'),
(7, 'Pozo Nuevo'),
(7, 'Pueblo Italiano'),
(7, 'Puesto de Castro'),
(7, 'Punta del Agua'),
(7, 'Quebracho Herrado'),
(7, 'Quilino'),
(7, 'Rafael Garc�a'),
(7, 'Ranqueles'),
(7, 'Rayo Cortado'),
(7, 'Reducci�n'),
(7, 'Rinc�n'),
(7, 'R�o Bamba'),
(7, 'R�o Ceballos'),
(7, 'R�o Cuarto'),
(7, 'R�o de Los Sauces'),
(7, 'R�o Primero'),
(7, 'R�o Segundo'),
(7, 'R�o Tercero'),
(7, 'Rosales'),
(7, 'Rosario del Saladillo'),
(7, 'Sacanta'),
(7, 'Sagrada Familia'),
(7, 'Saira'),
(7, 'Saladillo'),
(7, 'Sald�n'),
(7, 'Salsacate'),
(7, 'Salsipuedes'),
(7, 'Sampacho'),
(7, 'San Agust�n'),
(7, 'San Antonio de Arredondo'),
(7, 'San Antonio de Lit�n'),
(7, 'San Basilio'),
(7, 'San Carlos Minas'),
(7, 'San Clemente'),
(7, 'San Esteban'),
(7, 'San Francisco'),
(7, 'San Ignacio'),
(7, 'San Javier'),
(7, 'San Jer�nimo'),
(7, 'San Joaqu�n'),
(7, 'San Jos� de La Dormida'),
(7, 'San Jos� de Las Salinas'),
(7, 'San Lorenzo'),
(7, 'San Marcos Sierras'),
(7, 'San Marcos Sud'),
(7, 'San Pedro'),
(7, 'San Pedro N.'),
(7, 'San Roque'),
(7, 'San Vicente'),
(7, 'Santa Catalina'),
(7, 'Santa Elena'),
(7, 'Santa Eufemia'),
(7, 'Santa Maria'),
(7, 'Sarmiento'),
(7, 'Saturnino M.Laspiur'),
(7, 'Sauce Arriba'),
(7, 'Sebasti�n Elcano'),
(7, 'Seeber'),
(7, 'Segunda Usina'),
(7, 'Serrano'),
(7, 'Serrezuela'),
(7, 'Sgo. Temple'),
(7, 'Silvio Pellico'),
(7, 'Simbolar'),
(7, 'Sinsacate'),
(7, 'Sta. Rosa de Calamuchita'),
(7, 'Sta. Rosa de R�o Primero'),
(7, 'Suco'),
(7, 'Tala Ca�ada'),
(7, 'Tala Huasi'),
(7, 'Talaini'),
(7, 'Tancacha'),
(7, 'Tanti'),
(7, 'Ticino'),
(7, 'Tinoco'),
(7, 'T�o Pujio'),
(7, 'Toledo'),
(7, 'Toro Pujio'),
(7, 'Tosno'),
(7, 'Tosquita'),
(7, 'Tr�nsito'),
(7, 'Tuclame'),
(7, 'Tutti'),
(7, 'Ucacha'),
(7, 'Unquillo'),
(7, 'Valle de Anisacate'),
(7, 'Valle Hermoso'),
(7, 'V�lez Sarfield'),
(7, 'Viamonte'),
(7, 'Vicu�a Mackenna'),
(7, 'Villa Allende'),
(7, 'Villa Amancay'),
(7, 'Villa Ascasubi'),
(7, 'Villa Candelaria N.'),
(7, 'Villa Carlos Paz'),
(7, 'Villa Cerro Azul'),
(7, 'Villa Ciudad de Am�rica'),
(7, 'Villa Ciudad Pque Los Reartes'),
(7, 'Villa Concepci�n del T�o'),
(7, 'Villa Cura Brochero'),
(7, 'Villa de Las Rosas'),
(7, 'Villa de Mar�a'),
(7, 'Villa de Pocho'),
(7, 'Villa de Soto'),
(7, 'Villa del Dique'),
(7, 'Villa del Prado'),
(7, 'Villa del Rosario'),
(7, 'Villa del Totoral'),
(7, 'Villa Dolores'),
(7, 'Villa El Chancay'),
(7, 'Villa Elisa'),
(7, 'Villa Flor Serrana'),
(7, 'Villa Fontana'),
(7, 'Villa Giardino'),
(7, 'Villa Gral. Belgrano'),
(7, 'Villa Gutierrez'),
(7, 'Villa Huidobro'),
(7, 'Villa La Bolsa'),
(7, 'Villa Los Aromos'),
(7, 'Villa Los Patos'),
(7, 'Villa Mar�a'),
(7, 'Villa Nueva'),
(7, 'Villa Pque. Santa Ana'),
(7, 'Villa Pque. Siquiman'),
(7, 'Villa Quillinzo'),
(7, 'Villa Rossi'),
(7, 'Villa Rumipal'),
(7, 'Villa San Esteban'),
(7, 'Villa San Isidro'),
(7, 'Villa 21'),
(7, 'Villa Sarmiento (G.R)'),
(7, 'Villa Sarmiento (S.A)'),
(7, 'Villa Tulumba'),
(7, 'Villa Valeria'),
(7, 'Villa Yacanto'),
(7, 'Washington'),
(7, 'Wenceslao Escalante');

INSERT INTO Ciudades (IDProvincia, nombre) VALUES
(7, 'Ycho Cruz Sierras'),
(8, 'Alvear'),
(8, 'Bella Vista'),
(8, 'Ber�n de Astrada'),
(8, 'Bonpland'),
(8, 'Ca� Cati'),
(8, 'Capital'),
(8, 'Chavarr�a'),
(8, 'Col. C. Pellegrini'),
(8, 'Col. Libertad'),
(8, 'Col. Liebig'),
(8, 'Col. Sta Rosa'),
(8, 'Concepci�n'),
(8, 'Cruz de Los Milagros'),
(8, 'Curuz�-Cuati�'),
(8, 'Empedrado'),
(8, 'Esquina'),
(8, 'Estaci�n Torrent'),
(8, 'Felipe Yofr�'),
(8, 'Garruchos'),
(8, 'Gdor. Agr�nomo'),
(8, 'Gdor. Mart�nez'),
(8, 'Goya'),
(8, 'Guaviravi'),
(8, 'Herlitzka'),
(8, 'Ita-Ibate'),
(8, 'Itat�'),
(8, 'Ituzaing�'),
(8, 'Jos� Rafael G�mez'),
(8, 'Juan Pujol'),
(8, 'La Cruz'),
(8, 'Lavalle'),
(8, 'Lomas de Vallejos'),
(8, 'Loreto'),
(8, 'Mariano I. Loza'),
(8, 'Mburucuy�'),
(8, 'Mercedes'),
(8, 'Mocoret�'),
(8, 'Mte. Caseros'),
(8, 'Nueve de Julio'),
(8, 'Palmar Grande'),
(8, 'Parada Pucheta'),
(8, 'Paso de La Patria'),
(8, 'Paso de Los Libres'),
(8, 'Pedro R. Fernandez'),
(8, 'Perugorr�a'),
(8, 'Pueblo Libertador'),
(8, 'Ramada Paso'),
(8, 'Riachuelo'),
(8, 'Saladas'),
(8, 'San Antonio'),
(8, 'San Carlos'),
(8, 'San Cosme'),
(8, 'San Lorenzo'),
(8, '20 del Palmar'),
(8, 'San Miguel'),
(8, 'San Roque'),
(8, 'Santa Ana'),
(8, 'Santa Luc�a'),
(8, 'Santo Tom�'),
(8, 'Sauce'),
(8, 'Tabay'),
(8, 'Tapebicu�'),
(8, 'Tatacua'),
(8, 'Virasoro'),
(8, 'Yapey�'),
(8, 'Yatait� Calle'),
(9, 'Alarc�n'),
(9, 'Alcaraz'),
(9, 'Alcaraz N.'),
(9, 'Alcaraz S.'),
(9, 'Aldea Asunci�n'),
(9, 'Aldea Brasilera'),
(9, 'Aldea Elgenfeld'),
(9, 'Aldea Grapschental'),
(9, 'Aldea Ma. Luisa'),
(9, 'Aldea Protestante'),
(9, 'Aldea Salto'),
(9, 'Aldea San Antonio (G)'),
(9, 'Aldea San Antonio (P)'),
(9, 'Aldea 19'),
(9, 'Aldea San Miguel'),
(9, 'Aldea San Rafael'),
(9, 'Aldea Spatzenkutter'),
(9, 'Aldea Sta. Mar�a'),
(9, 'Aldea Sta. Rosa'),
(9, 'Aldea Valle Mar�a'),
(9, 'Altamirano Sur'),
(9, 'Antelo'),
(9, 'Antonio Tom�s'),
(9, 'Aranguren'),
(9, 'Arroyo Bar�'),
(9, 'Arroyo Burgos'),
(9, 'Arroyo Cl�'),
(9, 'Arroyo Corralito'),
(9, 'Arroyo del Medio'),
(9, 'Arroyo Maturrango'),
(9, 'Arroyo Palo Seco'),
(9, 'Banderas'),
(9, 'Basavilbaso'),
(9, 'Betbeder'),
(9, 'Bovril'),
(9, 'Caseros'),
(9, 'Ceibas'),
(9, 'Cerrito'),
(9, 'Chajar�'),
(9, 'Chilcas'),
(9, 'Clodomiro Ledesma'),
(9, 'Col. Alemana'),
(9, 'Col. Avellaneda'),
(9, 'Col. Avigdor'),
(9, 'Col. Ayu�'),
(9, 'Col. Baylina'),
(9, 'Col. Carrasco'),
(9, 'Col. Celina'),
(9, 'Col. Cerrito'),
(9, 'Col. Crespo'),
(9, 'Col. Elia'),
(9, 'Col. Ensayo'),
(9, 'Col. Gral. Roca'),
(9, 'Col. La Argentina'),
(9, 'Col. Merou'),
(9, 'Col. Oficial N�3'),
(9, 'Col. Oficial N�13'),
(9, 'Col. Oficial N�14'),
(9, 'Col. Oficial N�5'),
(9, 'Col. Reffino'),
(9, 'Col. Tunas'),
(9, 'Col. Virar�'),
(9, 'Col�n'),
(9, 'Concepci�n del Uruguay'),
(9, 'Concordia'),
(9, 'Conscripto Bernardi'),
(9, 'Costa Grande'),
(9, 'Costa San Antonio'),
(9, 'Costa Uruguay N.'),
(9, 'Costa Uruguay S.'),
(9, 'Crespo'),
(9, 'Crucecitas 3�'),
(9, 'Crucecitas 7�'),
(9, 'Crucecitas 8�'),
(9, 'Cuchilla Redonda'),
(9, 'Curtiembre'),
(9, 'Diamante'),
(9, 'Distrito 6�'),
(9, 'Distrito Cha�ar'),
(9, 'Distrito Chiqueros'),
(9, 'Distrito Cuarto'),
(9, 'Distrito Diego L�pez'),
(9, 'Distrito Pajonal'),
(9, 'Distrito Sauce'),
(9, 'Distrito Tala'),
(9, 'Distrito Talitas'),
(9, 'Don Crist�bal 1� Secci�n'),
(9, 'Don Crist�bal 2� Secci�n'),
(9, 'Durazno'),
(9, 'El Cimarr�n'),
(9, 'El Gramillal'),
(9, 'El Palenque'),
(9, 'El Pingo'),
(9, 'El Quebracho'),
(9, 'El Redom�n'),
(9, 'El Solar'),
(9, 'Enrique Carbo'),
(9, '9'),
(9, 'Espinillo N.'),
(9, 'Estaci�n Campos'),
(9, 'Estaci�n Escri�a'),
(9, 'Estaci�n Lazo'),
(9, 'Estaci�n Ra�ces'),
(9, 'Estaci�n Yer�a'),
(9, 'Estancia Grande'),
(9, 'Estancia L�baros'),
(9, 'Estancia Racedo'),
(9, 'Estancia Sol�'),
(9, 'Estancia Yuquer�'),
(9, 'Estaquitas'),
(9, 'Faustino M. Parera'),
(9, 'Febre'),
(9, 'Federaci�n'),
(9, 'Federal'),
(9, 'Gdor. Echag�e'),
(9, 'Gdor. Mansilla'),
(9, 'Gilbert'),
(9, 'Gonz�lez Calder�n'),
(9, 'Gral. Almada'),
(9, 'Gral. Alvear'),
(9, 'Gral. Campos'),
(9, 'Gral. Galarza'),
(9, 'Gral. Ram�rez'),
(9, 'Gualeguay'),
(9, 'Gualeguaych�'),
(9, 'Gualeguaycito'),
(9, 'Guardamonte'),
(9, 'Hambis'),
(9, 'Hasenkamp'),
(9, 'Hernandarias'),
(9, 'Hern�ndez'),
(9, 'Herrera'),
(9, 'Hinojal'),
(9, 'Hocker'),
(9, 'Ing. Sajaroff'),
(9, 'Irazusta'),
(9, 'Isletas'),
(9, 'J.J De Urquiza'),
(9, 'Jubileo'),
(9, 'La Clarita'),
(9, 'La Criolla'),
(9, 'La Esmeralda'),
(9, 'La Florida'),
(9, 'La Fraternidad'),
(9, 'La Hierra'),
(9, 'La Ollita'),
(9, 'La Paz'),
(9, 'La Picada'),
(9, 'La Providencia'),
(9, 'La Verbena'),
(9, 'Laguna Ben�tez'),
(9, 'Larroque'),
(9, 'Las Cuevas'),
(9, 'Las Garzas'),
(9, 'Las Guachas'),
(9, 'Las Mercedes'),
(9, 'Las Moscas'),
(9, 'Las Mulitas'),
(9, 'Las Toscas'),
(9, 'Laurencena'),
(9, 'Libertador San Mart�n'),
(9, 'Loma Limpia'),
(9, 'Los Ceibos'),
(9, 'Los Charruas'),
(9, 'Los Conquistadores'),
(9, 'Lucas Gonz�lez'),
(9, 'Lucas N.'),
(9, 'Lucas S. 1�'),
(9, 'Lucas S. 2�'),
(9, 'Maci�'),
(9, 'Mar�a Grande'),
(9, 'Mar�a Grande 2�'),
(9, 'M�danos'),
(9, 'Mojones N.'),
(9, 'Mojones S.'),
(9, 'Molino Doll'),
(9, 'Monte Redondo'),
(9, 'Montoya'),
(9, 'Mulas Grandes'),
(9, '�ancay'),
(9, 'Nogoy�'),
(9, 'Nueva Escocia'),
(9, 'Nueva Vizcaya'),
(9, 'Omb�'),
(9, 'Oro Verde'),
(9, 'Paran�'),
(9, 'Pasaje Guayaquil'),
(9, 'Pasaje Las Tunas'),
(9, 'Paso de La Arena'),
(9, 'Paso de La Laguna'),
(9, 'Paso de Las Piedras'),
(9, 'Paso Duarte'),
(9, 'Pastor Britos'),
(9, 'Pedernal'),
(9, 'Perdices'),
(9, 'Picada Ber�n'),
(9, 'Piedras Blancas'),
(9, 'Primer Distrito Cuchilla'),
(9, 'Primero de Mayo'),
(9, 'Pronunciamiento'),
(9, 'Pto. Algarrobo'),
(9, 'Pto. Ibicuy'),
(9, 'Pueblo Brugo'),
(9, 'Pueblo Cazes'),
(9, 'Pueblo Gral. Belgrano'),
(9, 'Pueblo Liebig'),
(9, 'Puerto Yeru�'),
(9, 'Punta del Monte'),
(9, 'Quebracho'),
(9, 'Quinto Distrito'),
(9, 'Raices Oeste'),
(9, 'Rinc�n de Nogoy�'),
(9, 'Rinc�n del Cinto'),
(9, 'Rinc�n del Doll'),
(9, 'Rinc�n del Gato'),
(9, 'Rocamora'),
(9, 'Rosario del Tala'),
(9, 'San Benito'),
(9, 'San Cipriano'),
(9, 'San Ernesto'),
(9, 'San Gustavo'),
(9, 'San Jaime'),
(9, 'San Jos�'),
(9, 'San Jos� de Feliciano'),
(9, 'San Justo'),
(9, 'San Marcial'),
(9, 'San Pedro'),
(9, 'San Ram�rez'),
(9, 'San Ram�n'),
(9, 'San Roque'),
(9, 'San Salvador'),
(9, 'San V�ctor'),
(9, 'Santa Ana'),
(9, 'Santa Anita'),
(9, 'Santa Elena'),
(9, 'Santa Luc�a'),
(9, 'Santa Luisa'),
(9, 'Sauce de Luna'),
(9, 'Sauce Montrull'),
(9, 'Sauce Pinto'),
(9, 'Sauce Sur'),
(9, 'Segu�'),
(9, 'Sir Leonard'),
(9, 'Sosa'),
(9, 'Tabossi'),
(9, 'Tezanos Pinto'),
(9, 'Ubajay'),
(9, 'Urdinarrain'),
(9, 'Veinte de Septiembre'),
(9, 'Viale'),
(9, 'Victoria'),
(9, 'Villa Clara'),
(9, 'Villa del Rosario'),
(9, 'Villa Dom�nguez'),
(9, 'Villa Elisa'),
(9, 'Villa Fontana'),
(9, 'Villa Gdor. Etchevehere'),
(9, 'Villa Mantero'),
(9, 'Villa Paranacito'),
(9, 'Villa Urquiza'),
(9, 'Villaguay'),
(9, 'Walter Moss'),
(9, 'Yacar�'),
(9, 'Yeso Oeste'),
(10, 'Buena Vista'),
(10, 'Clorinda'),
(10, 'Col. Pastoril'),
(10, 'Cte. Fontana'),
(10, 'El Colorado'),
(10, 'El Espinillo'),
(10, 'Estanislao Del Campo'),
(10, '10'),
(10, 'Fort�n Lugones'),
(10, 'Gral. Lucio V. Mansilla'),
(10, 'Gral. Manuel Belgrano'),
(10, 'Gral. Mosconi'),
(10, 'Gran Guardia'),
(10, 'Herradura'),
(10, 'Ibarreta'),
(10, 'Ing. Ju�rez'),
(10, 'Laguna Blanca'),
(10, 'Laguna Naick Neck'),
(10, 'Laguna Yema'),
(10, 'Las Lomitas'),
(10, 'Los Chiriguanos'),
(10, 'Mayor V. Villafa�e'),
(10, 'Misi�n San Fco.'),
(10, 'Palo Santo'),
(10, 'Piran�'),
(10, 'Pozo del Maza'),
(10, 'Riacho He-He'),
(10, 'San Hilario'),
(10, 'San Mart�n II'),
(10, 'Siete Palmas'),
(10, 'Subteniente Per�n'),
(10, 'Tres Lagunas'),
(10, 'Villa Dos Trece'),
(10, 'Villa Escolar'),
(10, 'Villa Gral. G�emes'),
(11, 'Abdon Castro Tolay'),
(11, 'Abra Pampa'),
(11, 'Abralaite'),
(11, 'Aguas Calientes'),
(11, 'Arrayanal'),
(11, 'Barrios'),
(11, 'Caimancito'),
(11, 'Calilegua'),
(11, 'Cangrejillos'),
(11, 'Caspala'),
(11, 'Catu�'),
(11, 'Cieneguillas'),
(11, 'Coranzulli'),
(11, 'Cusi-Cusi'),
(11, 'El Aguilar'),
(11, 'El Carmen'),
(11, 'El C�ndor'),
(11, 'El Fuerte'),
(11, 'El Piquete'),
(11, 'El Talar'),
(11, 'Fraile Pintado'),
(11, 'Hip�lito Yrigoyen'),
(11, 'Huacalera'),
(11, 'Humahuaca'),
(11, 'La Esperanza'),
(11, 'La Mendieta'),
(11, 'La Quiaca'),
(11, 'Ledesma'),
(11, 'Libertador Gral. San Martin'),
(11, 'Maimara'),
(11, 'Mina Pirquitas'),
(11, 'Monterrico'),
(11, 'Palma Sola'),
(11, 'Palpal�'),
(11, 'Pampa Blanca'),
(11, 'Pampichuela'),
(11, 'Perico'),
(11, 'Puesto del Marqu�s'),
(11, 'Puesto Viejo'),
(11, 'Pumahuasi'),
(11, 'Purmamarca'),
(11, 'Rinconada'),
(11, 'Rodeitos'),
(11, 'Rosario de R�o Grande'),
(11, 'San Antonio'),
(11, 'San Francisco'),
(11, 'San Pedro'),
(11, 'San Rafael'),
(11, 'San Salvador'),
(11, 'Santa Ana'),
(11, 'Santa Catalina'),
(11, 'Santa Clara'),
(11, 'Susques'),
(11, 'Tilcara'),
(11, 'Tres Cruces'),
(11, 'Tumbaya'),
(11, 'Valle Grande'),
(11, 'Vinalito'),
(11, 'Volc�n'),
(11, 'Yala'),
(11, 'Yav�'),
(11, 'Yuto'),
(12, 'Abramo'),
(12, 'Adolfo Van Praet'),
(12, 'Agustoni'),
(12, 'Algarrobo del Aguila'),
(12, 'Alpachiri'),
(12, 'Alta Italia'),
(12, 'Anguil'),
(12, 'Arata'),
(12, 'Ataliva Roca'),
(12, 'Bernardo Larroude'),
(12, 'Bernasconi'),
(12, 'Caleuf�'),
(12, 'Carro Quemado'),
(12, 'Catril�'),
(12, 'Ceballos'),
(12, 'Chacharramendi'),
(12, 'Col. Bar�n'),
(12, 'Col. Santa Mar�a'),
(12, 'Conhelo'),
(12, 'Coronel Hilario Lagos'),
(12, 'Cuchillo-C�'),
(12, 'Doblas'),
(12, 'Dorila'),
(12, 'Eduardo Castex'),
(12, 'Embajador Martini'),
(12, 'Falucho'),
(12, 'Gral. Acha'),
(12, 'Gral. Manuel Campos'),
(12, 'Gral. Pico'),
(12, 'Guatrach�'),
(12, 'Ing. Luiggi'),
(12, 'Intendente Alvear'),
(12, 'Jacinto Arauz'),
(12, 'La Adela'),
(12, 'La Humada'),
(12, 'La Maruja'),
(12, '12'),
(12, 'La Reforma'),
(12, 'Limay Mahuida'),
(12, 'Lonquimay'),
(12, 'Loventuel'),
(12, 'Luan Toro'),
(12, 'Macach�n'),
(12, 'Maisonnave'),
(12, 'Mauricio Mayer'),
(12, 'Metileo'),
(12, 'Miguel Can�'),
(12, 'Miguel Riglos'),
(12, 'Monte Nievas'),
(12, 'Parera'),
(12, 'Per�'),
(12, 'Pichi-Huinca'),
(12, 'Puelches'),
(12, 'Puel�n'),
(12, 'Quehue'),
(12, 'Quem� Quem�'),
(12, 'Quetrequ�n'),
(12, 'Rancul'),
(12, 'Realic�'),
(12, 'Relmo'),
(12, 'Rol�n'),
(12, 'Rucanelo'),
(12, 'Sarah'),
(12, 'Speluzzi'),
(12, 'Sta. Isabel'),
(12, 'Sta. Rosa'),
(12, 'Sta. Teresa'),
(12, 'Tel�n'),
(12, 'Toay'),
(12, 'Tomas M. de Anchorena'),
(12, 'Trenel'),
(12, 'Unanue'),
(12, 'Uriburu'),
(12, 'Veinticinco de Mayo'),
(12, 'Vertiz'),
(12, 'Victorica'),
(12, 'Villa Mirasol'),
(12, 'Winifreda'),
(13, 'Arauco'),
(13, 'Capital'),
(13, 'Castro Barros'),
(13, 'Chamical'),
(13, 'Chilecito'),
(13, 'Coronel F. Varela'),
(13, 'Famatina'),
(13, 'Gral. A.V.Pe�aloza'),
(13, 'Gral. Belgrano'),
(13, 'Gral. J.F. Quiroga'),
(13, 'Gral. Lamadrid'),
(13, 'Gral. Ocampo'),
(13, 'Gral. San Mart�n'),
(13, 'Independencia'),
(13, 'Rosario Penaloza'),
(13, 'San Blas de Los Sauces'),
(13, 'Sanagasta'),
(13, 'Vinchina'),
(14, 'Capital'),
(14, 'Chacras de Coria'),
(14, 'Dorrego'),
(14, 'Gllen'),
(14, 'Godoy Cruz'),
(14, 'Gral. Alvear'),
(14, 'Guaymall�n'),
(14, 'Jun�n'),
(14, 'La Paz'),
(14, 'Las Heras'),
(14, 'Lavalle'),
(14, 'Luj�n'),
(14, 'Luj�n De Cuyo'),
(14, 'Maip�'),
(14, 'Malarg�e'),
(14, 'Rivadavia'),
(14, 'San Carlos'),
(14, 'San Mart�n'),
(14, 'San Rafael'),
(14, 'Sta. Rosa'),
(14, 'Tunuy�n'),
(14, 'Tupungato'),
(14, 'Villa Nueva'),
(15, 'Alba Posse'),
(15, 'Almafuerte'),
(15, 'Ap�stoles'),
(15, 'Arist�bulo Del Valle'),
(15, 'Arroyo Del Medio'),
(15, 'Azara'),
(15, 'Bdo. De Irigoyen'),
(15, 'Bonpland'),
(15, 'Ca� Yari'),
(15, 'Campo Grande'),
(15, 'Campo Ram�n'),
(15, 'Campo Viera'),
(15, 'Candelaria'),
(15, 'Capiov�'),
(15, 'Caraguatay'),
(15, 'Cdte. Guacurar�'),
(15, 'Cerro Azul'),
(15, 'Cerro Cor�'),
(15, 'Col. Alberdi'),
(15, 'Col. Aurora'),
(15, 'Col. Delicia'),
(15, 'Col. Polana'),
(15, 'Col. Victoria'),
(15, 'Col. Wanda'),
(15, 'Concepci�n De La Sierra'),
(15, 'Corpus'),
(15, 'Dos Arroyos'),
(15, 'Dos de Mayo'),
(15, 'El Alc�zar'),
(15, 'El Dorado'),
(15, 'El Soberbio'),
(15, 'Esperanza'),
(15, 'F. Ameghino'),
(15, 'Fachinal'),
(15, 'Garuhap�'),
(15, 'Garup�'),
(15, 'Gdor. L�pez'),
(15, 'Gdor. Roca'),
(15, 'Gral. Alvear'),
(15, 'Gral. Urquiza'),
(15, 'Guaran�'),
(15, 'H. Yrigoyen'),
(15, 'Iguaz�'),
(15, 'Itacaruar�'),
(15, 'Jard�n Am�rica'),
(15, 'Leandro N. Alem'),
(15, 'Libertad'),
(15, 'Loreto'),
(15, 'Los Helechos'),
(15, 'M�rtires'),
(15, '15'),
(15, 'Moj�n Grande'),
(15, 'Montecarlo'),
(15, 'Nueve de Julio'),
(15, 'Ober�'),
(15, 'Olegario V. Andrade'),
(15, 'Panamb�'),
(15, 'Posadas'),
(15, 'Profundidad'),
(15, 'Pto. Iguaz�'),
(15, 'Pto. Leoni'),
(15, 'Pto. Piray'),
(15, 'Pto. Rico'),
(15, 'Ruiz de Montoya'),
(15, 'San Antonio'),
(15, 'San Ignacio'),
(15, 'San Javier'),
(15, 'San Jos�'),
(15, 'San Mart�n'),
(15, 'San Pedro'),
(15, 'San Vicente'),
(15, 'Santiago De Liniers'),
(15, 'Santo Pipo'),
(15, 'Sta. Ana'),
(15, 'Sta. Mar�a'),
(15, 'Tres Capones'),
(15, 'Veinticinco de Mayo'),
(15, 'Wanda'),
(16, 'Aguada San Roque'),
(16, 'Alumin�'),
(16, 'Andacollo'),
(16, 'A�elo'),
(16, 'Bajada del Agrio'),
(16, 'Barrancas'),
(16, 'Buta Ranquil'),
(16, 'Capital'),
(16, 'Caviahu�'),
(16, 'Centenario'),
(16, 'Chorriaca'),
(16, 'Chos Malal'),
(16, 'Cipolletti'),
(16, 'Covunco Abajo'),
(16, 'Coyuco Cochico'),
(16, 'Cutral C�'),
(16, 'El Cholar'),
(16, 'El Huec�'),
(16, 'El Sauce'),
(16, 'Gua�acos'),
(16, 'Huinganco'),
(16, 'Las Coloradas'),
(16, 'Las Lajas'),
(16, 'Las Ovejas'),
(16, 'Loncopu�'),
(16, 'Los Catutos'),
(16, 'Los Chihuidos'),
(16, 'Los Miches'),
(16, 'Manzano Amargo'),
(16, '16'),
(16, 'Octavio Pico'),
(16, 'Paso Aguerre'),
(16, 'Pic�n Leuf�'),
(16, 'Piedra del Aguila'),
(16, 'Pilo Lil'),
(16, 'Plaza Huincul'),
(16, 'Plottier'),
(16, 'Quili Malal'),
(16, 'Ram�n Castro'),
(16, 'Rinc�n de Los Sauces'),
(16, 'San Mart�n de Los Andes'),
(16, 'San Patricio del Cha�ar'),
(16, 'Santo Tom�s'),
(16, 'Sauzal Bonito'),
(16, 'Senillosa'),
(16, 'Taquimil�n'),
(16, 'Tricao Malal'),
(16, 'Varvarco'),
(16, 'Villa Cur� Leuvu'),
(16, 'Villa del Nahueve'),
(16, 'Villa del Puente Pic�n Leuv�'),
(16, 'Villa El Choc�n'),
(16, 'Villa La Angostura'),
(16, 'Villa Pehuenia'),
(16, 'Villa Traful'),
(16, 'Vista Alegre'),
(16, 'Zapala'),
(17, 'Aguada Cecilio'),
(17, 'Aguada de Guerra'),
(17, 'All�n'),
(17, 'Arroyo de La Ventana');

INSERT INTO Ciudades (IDProvincia, nombre) VALUES
(17, 'Arroyo Los Berros'),
(17, 'Bariloche'),
(17, 'Calte. Cordero'),
(17, 'Campo Grande'),
(17, 'Catriel'),
(17, 'Cerro Polic�a'),
(17, 'Cervantes'),
(17, 'Chelforo'),
(17, 'Chimpay'),
(17, 'Chinchinales'),
(17, 'Chipauquil'),
(17, 'Choele Choel'),
(17, 'Cinco Saltos'),
(17, 'Cipolletti'),
(17, 'Clemente Onelli'),
(17, 'Col�n Conhue'),
(17, 'Comallo'),
(17, 'Comic�'),
(17, 'Cona Niyeu'),
(17, 'Coronel Belisle'),
(17, 'Cubanea'),
(17, 'Darwin'),
(17, 'Dina Huapi'),
(17, 'El Bols�n'),
(17, 'El Ca�n'),
(17, 'El Manso'),
(17, 'Gral. Conesa'),
(17, 'Gral. Enrique Godoy'),
(17, 'Gral. Fernandez Oro'),
(17, 'Gral. Roca'),
(17, 'Guardia Mitre'),
(17, 'Ing. Huergo'),
(17, 'Ing. Jacobacci'),
(17, 'Laguna Blanca'),
(17, 'Lamarque'),
(17, 'Las Grutas'),
(17, 'Los Menucos'),
(17, 'Luis Beltr�n'),
(17, 'Mainqu�'),
(17, 'Mamuel Choique'),
(17, 'Maquinchao'),
(17, 'Mencu�'),
(17, 'Mtro. Ramos Mexia'),
(17, 'Nahuel Niyeu'),
(17, 'Naupa Huen'),
(17, '�orquinco'),
(17, 'Ojos de Agua'),
(17, 'Paso de Agua'),
(17, 'Paso Flores'),
(17, 'Pe�as Blancas'),
(17, 'Pichi Mahuida'),
(17, 'Pilcaniyeu'),
(17, 'Pomona'),
(17, 'Prahuaniyeu'),
(17, 'Rinc�n Treneta'),
(17, 'R�o Chico'),
(17, 'R�o Colorado'),
(17, 'Roca'),
(17, 'San Antonio Oeste'),
(17, 'San Javier'),
(17, 'Sierra Colorada'),
(17, 'Sierra Grande'),
(17, 'Sierra Pailem�n'),
(17, 'Valcheta'),
(17, 'Valle Azul'),
(17, 'Viedma'),
(17, 'Villa Llanqu�n'),
(17, 'Villa Mascardi'),
(17, 'Villa Regina'),
(17, 'Yaminu�'),
(18, 'A. Saravia'),
(18, 'Aguaray'),
(18, 'Angastaco'),
(18, 'Animan�'),
(18, 'Cachi'),
(18, 'Cafayate'),
(18, 'Campo Quijano'),
(18, 'Campo Santo'),
(18, 'Capital'),
(18, 'Cerrillos'),
(18, 'Chicoana'),
(18, 'Col. Sta. Rosa'),
(18, 'Coronel Moldes'),
(18, 'El Bordo'),
(18, 'El Carril'),
(18, 'El Galp�n'),
(18, 'El Jard�n'),
(18, 'El Potrero'),
(18, 'El Quebrachal'),
(18, 'El Tala'),
(18, 'Embarcaci�n'),
(18, 'Gral. Ballivian'),
(18, 'Gral. G�emes'),
(18, 'Gral. Mosconi'),
(18, 'Gral. Pizarro'),
(18, 'Guachipas'),
(18, 'Hip�lito Yrigoyen'),
(18, 'Iruy�'),
(18, 'Isla De Ca�as'),
(18, 'J. V. Gonzalez'),
(18, 'La Caldera'),
(18, 'La Candelaria'),
(18, 'La Merced'),
(18, 'La Poma'),
(18, 'La Vi�a'),
(18, 'Las Lajitas'),
(18, 'Los Toldos'),
(18, 'Met�n'),
(18, 'Molinos'),
(18, 'Nazareno'),
(18, 'Or�n'),
(18, 'Payogasta'),
(18, 'Pichanal'),
(18, 'Prof. S. Mazza'),
(18, 'R�o Piedras'),
(18, 'Rivadavia Banda Norte'),
(18, 'Rivadavia Banda Sur'),
(18, 'Rosario de La Frontera'),
(18, 'Rosario de Lerma'),
(18, 'Saclant�s'),
(18, '18'),
(18, 'San Antonio'),
(18, 'San Carlos'),
(18, 'San Jos� De Met�n'),
(18, 'San Ram�n'),
(18, 'Santa Victoria E.'),
(18, 'Santa Victoria O.'),
(18, 'Tartagal'),
(18, 'Tolar Grande'),
(18, 'Urundel'),
(18, 'Vaqueros'),
(18, 'Villa San Lorenzo'),
(19, 'Albard�n'),
(19, 'Angaco'),
(19, 'Calingasta'),
(19, 'Capital'),
(19, 'Caucete'),
(19, 'Chimbas'),
(19, 'Iglesia'),
(19, 'Jachal'),
(19, 'Nueve de Julio'),
(19, 'Pocito'),
(19, 'Rawson'),
(19, 'Rivadavia'),
(19, '19'),
(19, 'San Mart�n'),
(19, 'Santa Luc�a'),
(19, 'Sarmiento'),
(19, 'Ullum'),
(19, 'Valle F�rtil'),
(19, 'Veinticinco de Mayo'),
(19, 'Zonda'),
(20, 'Alto Pelado'),
(20, 'Alto Pencoso'),
(20, 'Anchorena'),
(20, 'Arizona'),
(20, 'Bagual'),
(20, 'Balde'),
(20, 'Batavia'),
(20, 'Beazley'),
(20, 'Buena Esperanza'),
(20, 'Candelaria'),
(20, 'Capital'),
(20, 'Carolina'),
(20, 'Carpinter�a'),
(20, 'Concar�n'),
(20, 'Cortaderas'),
(20, 'El Morro'),
(20, 'El Trapiche'),
(20, 'El Volc�n'),
(20, 'Fort�n El Patria'),
(20, 'Fortuna'),
(20, 'Fraga'),
(20, 'Juan Jorba'),
(20, 'Juan Llerena'),
(20, 'Juana Koslay'),
(20, 'Justo Daract'),
(20, 'La Calera'),
(20, 'La Florida'),
(20, 'La Punilla'),
(20, 'La Toma'),
(20, 'Lafinur'),
(20, 'Las Aguadas'),
(20, 'Las Chacras'),
(20, 'Las Lagunas'),
(20, 'Las Vertientes'),
(20, 'Lavaisse'),
(20, 'Leandro N. Alem'),
(20, 'Los Molles'),
(20, 'Luj�n'),
(20, 'Mercedes'),
(20, 'Merlo'),
(20, 'Naschel'),
(20, 'Navia'),
(20, 'Nogol�'),
(20, 'Nueva Galia'),
(20, 'Papagayos'),
(20, 'Paso Grande'),
(20, 'Potrero de Los Funes'),
(20, 'Quines'),
(20, 'Renca'),
(20, 'Saladillo'),
(20, 'San Francisco'),
(20, 'San Ger�nimo'),
(20, 'San Mart�n'),
(20, 'San Pablo'),
(20, 'Santa Rosa de Conlara'),
(20, 'Talita'),
(20, 'Tilisarao'),
(20, 'Uni�n'),
(20, 'Villa de La Quebrada'),
(20, 'Villa de Praga'),
(20, 'Villa del Carmen'),
(20, 'Villa Gral. Roca'),
(20, 'Villa Larca'),
(20, 'Villa Mercedes'),
(20, 'Zanjitas'),
(21, 'Calafate'),
(21, 'Caleta Olivia'),
(21, 'Ca�ad�n Seco'),
(21, 'Comandante Piedrabuena'),
(21, 'El Calafate'),
(21, 'El Chalt�n'),
(21, 'Gdor. Gregores'),
(21, 'Hip�lito Yrigoyen'),
(21, 'Jaramillo'),
(21, 'Koluel Kaike'),
(21, 'Las Heras'),
(21, 'Los Antiguos'),
(21, 'Perito Moreno'),
(21, 'Pico Truncado'),
(21, 'Pto. Deseado'),
(21, 'Pto. San Juli�n'),
(21, 'Pto. 21'),
(21, 'R�o Cuarto'),
(21, 'R�o Gallegos'),
(21, 'R�o Turbio'),
(21, 'Tres Lagos'),
(21, 'Veintiocho De Noviembre'),
(22, 'Aar�n Castellanos'),
(22, 'Acebal'),
(22, 'Aguar� Grande'),
(22, 'Albarellos'),
(22, 'Alcorta'),
(22, 'Aldao'),
(22, 'Alejandra'),
(22, '�lvarez'),
(22, 'Ambrosetti'),
(22, 'Amen�bar'),
(22, 'Ang�lica'),
(22, 'Angeloni'),
(22, 'Arequito'),
(22, 'Arminda'),
(22, 'Armstrong'),
(22, 'Arocena'),
(22, 'Arroyo Aguiar'),
(22, 'Arroyo Ceibal'),
(22, 'Arroyo Leyes'),
(22, 'Arroyo Seco'),
(22, 'Arruf�'),
(22, 'Arteaga'),
(22, 'Ataliva'),
(22, 'Aurelia'),
(22, 'Avellaneda'),
(22, 'Barrancas'),
(22, 'Bauer Y Sigel'),
(22, 'Bella Italia'),
(22, 'Berabev�'),
(22, 'Berna'),
(22, 'Bernardo de Irigoyen'),
(22, 'Bigand'),
(22, 'Bombal'),
(22, 'Bouquet'),
(22, 'Bustinza'),
(22, 'Cabal'),
(22, 'Cacique Ariacaiquin'),
(22, 'Cafferata'),
(22, 'Calchaqu�'),
(22, 'Campo Andino'),
(22, 'Campo Piaggio'),
(22, 'Ca�ada de G�mez'),
(22, 'Ca�ada del Ucle'),
(22, 'Ca�ada Rica'),
(22, 'Ca�ada Rosqu�n'),
(22, 'Candioti'),
(22, 'Capital'),
(22, 'Capit�n Berm�dez'),
(22, 'Capivara'),
(22, 'Carcara��'),
(22, 'Carlos Pellegrini'),
(22, 'Carmen'),
(22, 'Carmen Del Sauce'),
(22, 'Carreras'),
(22, 'Carrizales'),
(22, 'Casalegno'),
(22, 'Casas'),
(22, 'Casilda'),
(22, 'Castelar'),
(22, 'Castellanos'),
(22, 'Cayast�'),
(22, 'Cayastacito'),
(22, 'Centeno'),
(22, 'Cepeda'),
(22, 'Ceres'),
(22, 'Chab�s'),
(22, 'Cha�ar Ladeado'),
(22, 'Chapuy'),
(22, 'Chovet'),
(22, 'Christophersen'),
(22, 'Classon'),
(22, 'Cnel. Arnold'),
(22, 'Cnel. Bogado'),
(22, 'Cnel. Dominguez'),
(22, 'Cnel. Fraga'),
(22, 'Col. Aldao'),
(22, 'Col. Ana'),
(22, 'Col. Belgrano'),
(22, 'Col. Bicha'),
(22, 'Col. Bigand'),
(22, 'Col. Bossi'),
(22, 'Col. Cavour'),
(22, 'Col. Cello'),
(22, 'Col. Dolores'),
(22, 'Col. Dos Rosas'),
(22, 'Col. Dur�n'),
(22, 'Col. Iturraspe'),
(22, 'Col. Margarita'),
(22, 'Col. Mascias'),
(22, 'Col. Raquel'),
(22, 'Col. Rosa'),
(22, 'Col. San Jos�'),
(22, 'Constanza'),
(22, 'Coronda'),
(22, 'Correa'),
(22, 'Crispi'),
(22, 'Culul�'),
(22, 'Curupayti'),
(22, 'Desvio Arij�n'),
(22, 'Diaz'),
(22, 'Diego de Alvear'),
(22, 'Egusquiza'),
(22, 'El Araz�'),
(22, 'El Rab�n'),
(22, 'El Sombrerito'),
(22, 'El Tr�bol'),
(22, 'Elisa'),
(22, 'Elortondo'),
(22, 'Emilia'),
(22, 'Empalme San Carlos'),
(22, 'Empalme Villa Constitucion'),
(22, 'Esmeralda'),
(22, 'Esperanza'),
(22, 'Estaci�n Alvear'),
(22, 'Estacion Clucellas'),
(22, 'Esteban Rams'),
(22, 'Esther'),
(22, 'Esustolia'),
(22, 'Eusebia'),
(22, 'Felicia'),
(22, 'Fidela'),
(22, 'Fighiera'),
(22, 'Firmat'),
(22, 'Florencia'),
(22, 'Fort�n Olmos'),
(22, 'Franck'),
(22, 'Fray Luis Beltr�n'),
(22, 'Frontera'),
(22, 'Fuentes'),
(22, 'Funes'),
(22, 'Gaboto'),
(22, 'Galisteo'),
(22, 'G�lvez'),
(22, 'Garabalto'),
(22, 'Garibaldi'),
(22, 'Gato Colorado'),
(22, 'Gdor. Crespo'),
(22, 'Gessler'),
(22, 'Godoy'),
(22, 'Golondrina'),
(22, 'Gral. Gelly'),
(22, 'Gral. Lagos'),
(22, 'Granadero Baigorria'),
(22, 'Gregoria Perez De Denis'),
(22, 'Grutly'),
(22, 'Guadalupe N.'),
(22, 'G�deken'),
(22, 'Helvecia'),
(22, 'Hersilia'),
(22, 'Hipat�a'),
(22, 'Huanqueros'),
(22, 'Hugentobler'),
(22, 'Hughes'),
(22, 'Humberto 1�'),
(22, 'Humboldt'),
(22, 'Ibarlucea'),
(22, 'Ing. Chanourdie'),
(22, 'Intiyaco'),
(22, 'Ituzaing�'),
(22, 'Jacinto L. Ar�uz'),
(22, 'Josefina'),
(22, 'Juan B. Molina'),
(22, 'Juan de Garay'),
(22, 'Juncal'),
(22, 'La Brava'),
(22, 'La Cabral'),
(22, 'La Camila'),
(22, 'La Chispa'),
(22, 'La Clara'),
(22, 'La Criolla'),
(22, 'La Gallareta'),
(22, 'La Lucila'),
(22, 'La Pelada'),
(22, 'La Penca'),
(22, 'La Rubia'),
(22, 'La Sarita'),
(22, 'La Vanguardia'),
(22, 'Labordeboy'),
(22, 'Laguna Paiva'),
(22, 'Landeta'),
(22, 'Lanteri'),
(22, 'Larrechea'),
(22, 'Las Avispas'),
(22, 'Las Bandurrias'),
(22, 'Las Garzas'),
(22, 'Las Palmeras'),
(22, 'Las Parejas'),
(22, 'Las Petacas'),
(22, 'Las Rosas'),
(22, 'Las Toscas'),
(22, 'Las Tunas'),
(22, 'Lazzarino'),
(22, 'Lehmann'),
(22, 'Llambi Campbell'),
(22, 'Logro�o'),
(22, 'Loma Alta'),
(22, 'L�pez'),
(22, 'Los Amores'),
(22, 'Los Cardos'),
(22, 'Los Laureles'),
(22, 'Los Molinos'),
(22, 'Los Quirquinchos'),
(22, 'Lucio V. Lopez'),
(22, 'Luis Palacios'),
(22, 'Ma. Juana'),
(22, 'Ma. Luisa'),
(22, 'Ma. Susana'),
(22, 'Ma. Teresa'),
(22, 'Maciel'),
(22, 'Maggiolo'),
(22, 'Malabrigo'),
(22, 'Marcelino Escalada'),
(22, 'Margarita'),
(22, 'Matilde'),
(22, 'Mau�'),
(22, 'M�ximo Paz'),
(22, 'Melincu�'),
(22, 'Miguel Torres'),
(22, 'Mois�s Ville'),
(22, 'Monigotes'),
(22, 'Monje'),
(22, 'Monte Obscuridad'),
(22, 'Monte Vera'),
(22, 'Montefiore'),
(22, 'Montes de Oca'),
(22, 'Murphy'),
(22, '�anducita'),
(22, 'Nar�'),
(22, 'Nelson'),
(22, 'Nicanor E. Molinas'),
(22, 'Nuevo Torino'),
(22, 'Oliveros'),
(22, 'Palacios'),
(22, 'Pav�n'),
(22, 'Pav�n Arriba');

INSERT INTO Ciudades (IDProvincia, nombre) VALUES
(22, 'Pedro G�mez Cello'),
(22, 'P�rez'),
(22, 'Peyrano'),
(22, 'Piamonte'),
(22, 'Pilar'),
(22, 'Pi�ero'),
(22, 'Plaza Clucellas'),
(22, 'Portugalete'),
(22, 'Pozo Borrado'),
(22, 'Progreso'),
(22, 'Providencia'),
(22, 'Pte. Roca'),
(22, 'Pueblo Andino'),
(22, 'Pueblo Esther'),
(22, 'Pueblo Gral. San Mart�n'),
(22, 'Pueblo Irigoyen'),
(22, 'Pueblo Marini'),
(22, 'Pueblo Mu�oz'),
(22, 'Pueblo Uranga'),
(22, 'Pujato'),
(22, 'Pujato N.'),
(22, 'Rafaela'),
(22, 'Ramay�n'),
(22, 'Ramona'),
(22, 'Reconquista'),
(22, 'Recreo'),
(22, 'Ricardone'),
(22, 'Rivadavia'),
(22, 'Rold�n'),
(22, 'Romang'),
(22, 'Rosario'),
(22, 'Rueda'),
(22, 'Rufino'),
(22, 'Sa Pereira'),
(22, 'Saguier'),
(22, 'Saladero M. Cabal'),
(22, 'Salto Grande'),
(22, 'San Agust�n'),
(22, 'San Antonio de Obligado'),
(22, 'San Bernardo (N.J.)'),
(22, 'San Bernardo (S.J.)'),
(22, 'San Carlos Centro'),
(22, 'San Carlos N.'),
(22, 'San Carlos S.'),
(22, 'San Crist�bal'),
(22, 'San Eduardo'),
(22, 'San Eugenio'),
(22, 'San Fabi�n'),
(22, 'San Fco. de Santa F�'),
(22, 'San Genaro'),
(22, 'San Genaro N.'),
(22, 'San Gregorio'),
(22, 'San Guillermo'),
(22, 'San Javier'),
(22, 'San Jer�nimo del Sauce'),
(22, 'San Jer�nimo N.'),
(22, 'San Jer�nimo S.'),
(22, 'San Jorge'),
(22, 'San Jos� de La Esquina'),
(22, 'San Jos� del Rinc�n'),
(22, 'San Justo'),
(22, 'San Lorenzo'),
(22, 'San Mariano'),
(22, 'San Mart�n de Las Escobas'),
(22, 'San Mart�n N.'),
(22, 'San Vicente'),
(22, 'Sancti Spititu'),
(22, 'Sanford'),
(22, 'Santo Domingo'),
(22, 'Santo Tom�'),
(22, 'Santurce'),
(22, 'Sargento Cabral'),
(22, 'Sarmiento'),
(22, 'Sastre'),
(22, 'Sauce Viejo'),
(22, 'Serodino'),
(22, 'Silva'),
(22, 'Soldini'),
(22, 'Soledad'),
(22, 'Soutomayor'),
(22, 'Sta. Clara de Buena Vista'),
(22, 'Sta. Clara de Saguier'),
(22, 'Sta. Isabel'),
(22, 'Sta. Margarita'),
(22, 'Sta. Maria Centro'),
(22, 'Sta. Mar�a N.'),
(22, 'Sta. Rosa'),
(22, 'Sta. Teresa'),
(22, 'Suardi'),
(22, 'Sunchales'),
(22, 'Susana'),
(22, 'Tacuarend�'),
(22, 'Tacural'),
(22, 'Tartagal'),
(22, 'Teodelina'),
(22, 'Theobald'),
(22, 'Timb�es'),
(22, 'Toba'),
(22, 'Tortugas'),
(22, 'Tostado'),
(22, 'Totoras'),
(22, 'Traill'),
(22, 'Venado Tuerto'),
(22, 'Vera'),
(22, 'Vera y Pintado'),
(22, 'Videla'),
(22, 'Vila'),
(22, 'Villa Amelia'),
(22, 'Villa Ana'),
(22, 'Villa Ca�as'),
(22, 'Villa Constituci�n'),
(22, 'Villa Elo�sa'),
(22, 'Villa Gdor. G�lvez'),
(22, 'Villa Guillermina'),
(22, 'Villa Minetti'),
(22, 'Villa Mugueta'),
(22, 'Villa Ocampo'),
(22, 'Villa San Jos�'),
(22, 'Villa Saralegui'),
(22, 'Villa Trinidad'),
(22, 'Villada'),
(22, 'Virginia'),
(22, 'Wheelwright'),
(22, 'Zavalla'),
(22, 'Zen�n Pereira'),
(23, 'A�atuya'),
(23, '�rraga'),
(23, 'Bandera'),
(23, 'Bandera Bajada'),
(23, 'Beltr�n'),
(23, 'Brea Pozo'),
(23, 'Campo Gallo'),
(23, 'Capital'),
(23, 'Chilca Juliana'),
(23, 'Choya'),
(23, 'Clodomira'),
(23, 'Col. Alpina'),
(23, 'Col. Dora'),
(23, 'Col. El Simbolar Robles'),
(23, 'El Bobadal'),
(23, 'El Charco'),
(23, 'El Moj�n'),
(23, 'Estaci�n Atamisqui'),
(23, 'Estaci�n Simbolar'),
(23, 'Fern�ndez'),
(23, 'Fort�n Inca'),
(23, 'Fr�as'),
(23, 'Garza'),
(23, 'Gramilla'),
(23, 'Guardia Escolta'),
(23, 'Herrera'),
(23, 'Ica�o'),
(23, 'Ing. Forres'),
(23, 'La Banda'),
(23, 'La Ca�ada'),
(23, 'Laprida'),
(23, 'Lavalle'),
(23, 'Loreto'),
(23, 'Los Jur�es'),
(23, 'Los N��ez'),
(23, 'Los Pirpintos'),
(23, 'Los Quiroga'),
(23, 'Los Telares'),
(23, 'Lugones'),
(23, 'Malbr�n'),
(23, 'Matara'),
(23, 'Medell�n'),
(23, 'Monte Quemado'),
(23, 'Nueva Esperanza'),
(23, 'Nueva Francia'),
(23, 'Palo Negro'),
(23, 'Pampa de Los Guanacos'),
(23, 'Pinto'),
(23, 'Pozo Hondo'),
(23, 'Quimil�'),
(23, 'Real Sayana'),
(23, 'Sachayoj'),
(23, 'San Pedro de Guasay�n'),
(23, 'Selva'),
(23, 'Sol de Julio'),
(23, 'Sumampa'),
(23, 'Suncho Corral'),
(23, 'Taboada'),
(23, 'Tapso'),
(23, 'Termas de Rio Hondo'),
(23, 'Tintina'),
(23, 'Tomas Young'),
(23, 'Vilelas'),
(23, 'Villa Atamisqui'),
(23, 'Villa La Punta'),
(23, 'Villa Ojo de Agua'),
(23, 'Villa R�o Hondo'),
(23, 'Villa Salavina'),
(23, 'Villa Uni�n'),
(23, 'Vilmer'),
(23, 'Weisburd'),
(24, 'R�o Grande'),
(24, 'Tolhuin'),
(24, 'Ushuaia'),
(25, 'Acheral'),
(25, 'Agua Dulce'),
(25, 'Aguilares'),
(25, 'Alderetes'),
(25, 'Alpachiri'),
(25, 'Alto Verde'),
(25, 'Amaicha del Valle'),
(25, 'Amberes'),
(25, 'Ancajuli'),
(25, 'Arcadia'),
(25, 'Atahona'),
(25, 'Banda del R�o Sali'),
(25, 'Bella Vista'),
(25, 'Buena Vista'),
(25, 'Burruyac�'),
(25, 'Capit�n C�ceres'),
(25, 'Cevil Redondo'),
(25, 'Choromoro'),
(25, 'Ciudacita'),
(25, 'Colalao del Valle'),
(25, 'Colombres'),
(25, 'Concepci�n'),
(25, 'Delf�n Gallo'),
(25, 'El Bracho'),
(25, 'El Cadillal'),
(25, 'El Cercado'),
(25, 'El Cha�ar'),
(25, 'El Manantial'),
(25, 'El Moj�n'),
(25, 'El Mollar'),
(25, 'El Naranjito'),
(25, 'El Naranjo'),
(25, 'El Polear'),
(25, 'El Puestito'),
(25, 'El Sacrificio'),
(25, 'El Timb�'),
(25, 'Escaba'),
(25, 'Esquina'),
(25, 'Estaci�n Ar�oz'),
(25, 'Famaill�'),
(25, 'Gastone'),
(25, 'Gdor. Garmendia'),
(25, 'Gdor. Piedrabuena'),
(25, 'Graneros'),
(25, 'Huasa Pampa'),
(25, 'J. B. Alberdi'),
(25, 'La Cocha'),
(25, 'La Esperanza'),
(25, 'La Florida'),
(25, 'La Ramada'),
(25, 'La Trinidad'),
(25, 'Lamadrid'),
(25, 'Las Cejas'),
(25, 'Las Talas'),
(25, 'Las Talitas'),
(25, 'Los Bulacio'),
(25, 'Los G�mez'),
(25, 'Los Nogales'),
(25, 'Los Pereyra'),
(25, 'Los P�rez'),
(25, 'Los Puestos'),
(25, 'Los Ralos'),
(25, 'Los Sarmientos'),
(25, 'Los Sosa'),
(25, 'Lules'),
(25, 'M. Garc�a Fern�ndez'),
(25, 'Manuela Pedraza'),
(25, 'Medinas'),
(25, 'Monte Bello'),
(25, 'Monteagudo'),
(25, 'Monteros'),
(25, 'Padre Monti'),
(25, 'Pampa Mayo'),
(25, 'Quilmes'),
(25, 'Raco'),
(25, 'Ranchillos'),
(25, 'R�o Chico'),
(25, 'R�o Colorado'),
(25, 'R�o Seco'),
(25, 'Rumi Punco'),
(25, 'San Andr�s'),
(25, 'San Felipe'),
(25, 'San Ignacio'),
(25, 'San Javier'),
(25, 'San Jos�'),
(25, 'San Miguel de 25'),
(25, 'San Pedro'),
(25, 'San Pedro de Colalao'),
(25, 'Santa Rosa de Leales'),
(25, 'Sgto. Moya'),
(25, 'Siete de Abril'),
(25, 'Simoca'),
(25, 'Soldado Maldonado'),
(25, 'Sta. Ana'),
(25, 'Sta. Cruz'),
(25, 'Sta. Luc�a'),
(25, 'Taco Ralo'),
(25, 'Taf� del Valle'),
(25, 'Taf� Viejo'),
(25, 'Tapia'),
(25, 'Teniente Berdina'),
(25, 'Trancas'),
(25, 'Villa Belgrano'),
(25, 'Villa Benjam�n Araoz'),
(25, 'Villa Chiligasta'),
(25, 'Villa de Leales'),
(25, 'Villa Quinteros'),
(25, 'Y�nima'),
(25, 'Yerba Buena'),
(25, 'Yerba Buena (S)');
